'''
Run GSEA using the csv generated by deg_analysis
'''
import pandas as pd
import gseapy as gp
import argparse
import os


def main():
    parser = argparse.ArgumentParser(description="GSEA analysis")
    parser.add_argument('--csv', type=str, required=True, help='Path to the csv file with LFC values')
    parser.add_argument('--output', type=str, required=True, help='Directory to save the GSEA results')
    parser.add_argument('--gene_sets', type=str, default="MSigDB_Hallmark_2020", 
                        help='Path to the gene sets file (GMT format or a string with names from GSEA). ' \
                        'If not provided, will use the default of MSigDB_Hallmark_2020.')
    args = parser.parse_args()
    if not os.path.exists(args.output):
        os.makedirs(args.output)

    # Load the csv file
    df = pd.read_csv(args.csv)
    # sort by LFC values
    df = df.sort_values(by='log_fc', ascending=False)
    df = df.loc[:, ['gene', 'log_fc']]
    df.columns = ['gene', 'score']

    pre_res = gp.prerank(
        rnk=df,
        gene_sets=args.gene_sets,
        processes=4,  # Use 4 processes for parallel computation
        outdir=args.output,
        format='png',  # Save plots in PNG format
        seed=42,  # Set a random seed for reproducibility
        verbose=True
    )
    # Save the prerank results
    pre_res.res2d.to_csv(os.path.join(args.output, 'gsea_results.csv'), index=True)


if __name__ == "__main__":
    main()