'''
Run GSEA using the csv generated by deg_analysis
'''
import pandas as pd
import gseapy as gp
import numpy as np
import argparse
import os
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
## plotting settings
if True:  # In order to bypass isort when saving
    from altairThemes import altairThemes
alt.themes.register("publishTheme", altairThemes.publishTheme)
alt.themes.enable("publishTheme")

def pre_rank(args):
    df = pd.read_csv(args.csv)
    try:
        df["score"] = df['log_fc']
    except KeyError:
        df["score"] = df['Coefficient']
    df = df.sort_values(by='score', ascending=False)
    df = df.loc[:, ['gene', 'score']]

    if args.mapping_dict:
        # Load the mapping dictionary
        template = pd.read_csv(args.mapping_dict, sep='\t')
        name_to_symbol = {row.iloc[0]: row.iloc[1] for _, row in template.iterrows()}  # map from gene symbol to name
        # Convert the gene names to gene symbols
        df['gene'] = df['gene'].map(name_to_symbol)
        # Drop rows with NaN values in the 'gene' column
        df = df.dropna(subset=['gene'])
        print("Size of the dataframe:", df.shape)        

    pre_res = gp.prerank(
        rnk=df,
        gene_sets=args.gene_sets,
        threads=4,
        min_size=1,
        max_size=10000,
        outdir=args.output,
        format='png',
        permutation_num=10000,
        seed=42,
        verbose=True
    )

    # Sort by NES and select top 10 UP enriched
    terms_sorted = pre_res.res2d.sort_values("NES", ascending=False)
    terms_sorted = terms_sorted[terms_sorted["FDR q-val"] < 0.25]
    # get only the entries after __
    terms_sorted["Term"] = terms_sorted["Term"].str.split("__").str[-1]

    # top10 positive
    top_terms_sorted = terms_sorted[terms_sorted["NES"] > 0]

    plt.figure(figsize=(10, 6))
    sns.barplot(
        x="NES",
        y="Term",
        data=top_terms_sorted,
        orient='h'
    )
    plt.title("Normalized Enrichment Scores (Top GSEA Hits)")

    plt.xlabel("Normalized Enrichment Score (NES)")
    plt.ylabel("Gene Set")
    plt.title("Top Positively Enriched Gene Sets")
    plt.tight_layout()
    plt.savefig(os.path.join(args.output, 'gsea_results_top.png'))
    plt.close()

    # Sort by NES and select top 10 DOWN enriched
    btm_terms_sorted = terms_sorted[terms_sorted["NES"] < 0]

    plt.figure(figsize=(10, 6))
    sns.barplot(
        x="NES",
        y="Term",
        data=btm_terms_sorted,
        orient='h'
    )
    # plt.axvline(0, color='gray', linestyle='--')
    plt.title("Normalized Enrichment Scores (Top GSEA Hits)")

    plt.xlabel("Normalized Enrichment Score (NES)")
    plt.ylabel("Gene Set")
    plt.title("Top Negatively Enriched Gene Sets")
    plt.tight_layout()
    plt.savefig(os.path.join(args.output, 'gsea_results_btm.png'))
    plt.close()

    # plot one altair showing the top positive and negative enrichment from pre-rank
    # make red more red for positive and blue more blue for negative based on the p-val
    altair_df = pd.DataFrame({
        "Term": pd.concat([top_terms_sorted["Term"], btm_terms_sorted["Term"]]),
        "NES": pd.concat([top_terms_sorted["NES"], btm_terms_sorted["NES"]]),
        "FDR q-val": pd.concat([top_terms_sorted["FDR q-val"], btm_terms_sorted["FDR q-val"]])
    })
    # filter such that we only have FDR q-val < 0.25
    altair_df = altair_df[altair_df["FDR q-val"] < 0.25]
    # plot with a scale
    chart = alt.Chart(altair_df).mark_bar().encode(
        x=alt.X('NES:Q', title='Normalized Enrichment Score (NES)'),
        y=alt.Y('Term:N', sort='-x', title='Gene Set'),
        color=alt.condition(
            alt.datum.NES > 0,
            alt.value('indianred'),  # Positive NES color
            alt.value('steelblue')   # Negative NES color
        )
    ).properties(
        title="Top Positively and Negatively Enriched Gene Sets",
    ).interactive()
    chart.save(os.path.join(args.output, 'gsea_results_top_btm_altair.html'))

    if args.comparisons:
        histogram_df = pd.DataFrame({"positive_NES": pre_res.res2d[pre_res.res2d["NES"] > 0]["Term"],
                                     "negative_NES": pre_res.res2d[pre_res.res2d["NES"] < 0]["Term"]})
        # compute the positive enrichment and negative enrichment for each comparison
        final_results_dict = {}
        for comp in args.comparisons:
            # get the number of rows where comp is a part of the term of each
            num_pos = np.sum(histogram_df["positive_NES"].str.contains(comp, case=False, na=False))
            num_neg = np.sum(histogram_df["negative_NES"].str.contains(comp, case=False, na=False))
            normalized_num_pos = num_pos / (num_pos + num_neg) if (num_pos + num_neg) > 0 else 0
            normalized_num_neg = num_neg / (num_pos + num_neg) if (num_pos + num_neg) > 0 else 0
            final_results_dict[comp] = [normalized_num_pos, normalized_num_neg]
        # plot size by side bar plot for all comparisons of positive and negative enrichment
        # make this in one plot
        plt.figure(figsize=(10, 6))
        comps = list(final_results_dict.keys())
        pos_values = [final_results_dict[comp][0] for comp in comps]
        neg_values = [final_results_dict[comp][1] for comp in comps]
        x = np.arange(len(comps))
        width = 0.35
        plt.bar(x - width/2, pos_values, width, label='Positive Enrichment')
        plt.bar(x + width/2, neg_values, width, label='Negative Enrichment')
        plt.xlabel('Comparisons')
        plt.ylabel('Relative Frequency')
        plt.title('Positive vs Negative Enrichment Across Comparisons')
        plt.xticks(x, comps, rotation=45, ha='right')
        plt.legend()
        plt.tight_layout()
        plt.savefig(os.path.join(args.output, f'enrichr_results_all_comparisons_sbs.png'))
        plt.close()
        # plot with altair
        altair_df = pd.DataFrame({
            "Comparison": comps * 2,
            "Enrichment": pos_values + neg_values,
            "Type": ["Positive"] * len(comps) + ["Negative"] * len(comps)
        })
        chart = alt.Chart(altair_df).mark_bar().encode(
            x=alt.X('Comparison:N', title='Comparisons', sort='-y'),
            y=alt.Y('Enrichment:Q', title='Relative Frequency'),
            color=alt.Color('Type:N', title='Enrichment Type', scale=alt.Scale(
                domain=['Positive', 'Negative'],
                range=['indianred', 'steelblue']
            ))
        ).properties(
            title="Positive vs Negative Enrichment Across Comparisons",
        ).interactive()
        chart.save(os.path.join(args.output, f'enrichr_results_all_comparisons_sbs_altair.html'))

def enrichr(args):
    # Load the csv file
    with open(args.txt, 'r') as f:
        genes = f.read().splitlines()
    
    if args.mapping_dict:
        # Load the mapping dictionary
        template = pd.read_csv(args.mapping_dict, sep='\t')
        name_to_symbol = {row.iloc[0]: row.iloc[1] for _, row in template.iterrows()}  # map from gene symbol to name
        # Convert the gene names to gene symbols
        df['gene'] = df['gene'].map(name_to_symbol)
        # Drop rows with NaN values in the 'gene' column
        df = df.dropna(subset=['gene'])
        print("Size of the dataframe:", df.shape)        

    enr_res = gp.enrichr(
        gene_list=genes,
        gene_sets=args.gene_sets,
        outdir=args.output,
        cutoff=0.25,  # Only consider terms with adj p-value < 0.25
        verbose=True
    )

    # Sort by combined score and select top 10 UP enriched
    top_terms_sorted = enr_res.results.sort_values("Combined Score", ascending=False)
    top_terms_sorted = top_terms_sorted[top_terms_sorted["Adjusted P-value"] < 0.25]
    top_terms_sorted = top_terms_sorted[top_terms_sorted["Combined Score"] > 0]
    plt.figure(figsize=(10, 6))
    sns.barplot(
        x="Combined Score",
        y="Term",
        data=top_terms_sorted,
        orient='h'
    )
    plt.title("Combined Scores (Top Enrichr Hits)")
    plt.xlabel("Combined Score")
    plt.ylabel("Gene Set")
    plt.title("Top Positively Enriched Gene Sets")
    plt.tight_layout()
    plt.savefig(os.path.join(args.output, 'enrichr_results_top.png'))
    plt.close()

    # plot with Altair
    altair_df = pd.DataFrame({
        "Term": top_terms_sorted["Term"],
        "Combined Score": top_terms_sorted["Combined Score"],
    })
    chart = alt.Chart(altair_df).mark_bar().encode(
        x=alt.X('Combined Score:Q', title='Combined Score'),
        y=alt.Y('Term:N', sort='-x', title='Gene Set'),
        color=alt.value('indianred')  # Color for bars
    ).properties(
        title="Top Positively Enriched Gene Sets (Enrichr)",
    ).interactive()
    chart.save(os.path.join(args.output, 'enrichr_results_top_altair.html'))

def main():
    parser = argparse.ArgumentParser(description="GSEA analysis")
    parser.add_argument('--csv', type=str, help='Path to the csv file with LFC values. Needed for prerank GSEA.')
    parser.add_argument('--txt', type=str, help='Path to the txt file with DE genes. Needed for enrichr GSEA.')
    parser.add_argument('--output', type=str, required=True, help='Directory to save the GSEA results')
    parser.add_argument('--mapping_dict', type=str, default=None, help='features.tsv file for converting gene names to gene symbols.')
    parser.add_argument('--gene_sets', type=str, nargs="+", default=["MSigDB_Hallmark_2020"], 
                        help='Path to the gene sets file (GMT format or a string with names from GSEA). ' \
                        'If not provided, will use the default of MSigDB_Hallmark_2020.')
    parser.add_argument("--comparisons", type=str, nargs="+", default=None, 
                        help='List of comparisons to analyze. It will generate a sbs bar plot for each comparison.')
    args = parser.parse_args()
    if not os.path.exists(args.output):
        os.makedirs(args.output)
    
    if args.csv:
        print("Running prerank GSEA...")
        pre_rank(args)
    elif args.txt:
        print("Running Enrichr GSEA...")
        enrichr(args)
    else:
        raise ValueError("Please provide either --csv for prerank GSEA or --txt for Enrichr GSEA.")

if __name__ == "__main__":
    main()